config/routes.rb
Rails.application.routes.draw do
  resources :battles
  root 'battles#index'
  get :stats , to: 'battles#stats'
  get :list  , to: 'battles#list'
  get :count , to: 'battles#count'
  get :search, to: 'battles#search'
end

app/models/battle.rb
class Battle < ActiveRecord::Base

  # Search the models table
  # searches the [column] for any occurences of [q]
  # @param column [Symbol]
  # @param q [String]
  # @return [Battle::ActiveRecord_Relation] search result
  scope :search, -> (column, q) do
    q="%#{q}%"
    where("#{column.to_s} ILIKE ?", q)
  end

  # Find the highest occuring value for any column
  # @param column [Symbol or String]
  # @return [String] highest occuring value
  def self.highest_freq(column)
    column = column.to_s
    Battle.select("#{column}, count(#{column})").group(column).order(count: :desc).limit(1)[0].send(column)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/battles_controller.rb
class BattlesController < ActionController::Base
  before_action :load_battle, only: [:show, :update, :destroy, :edit]
  before_action :load_atrs,   only: [:show, :edit, :new]
  layout 'application'

  def index
    @battles = Battle.all.order(:battle_number)

    respond_to do |format|

      format.html

      format.json {
        limit = (params[:limit] || 10).to_i
        offset = (params[:offset] || 0).to_i

        total_count = Battle.count
        battles = Battle.order(:battle_number).
          offset(offset).limit(limit)

        has_more = total_count - battles.size
        if has_more > 0
          new_offset = offset + limit
          next_url = "#{request.base_url+request.path}?offset=#{new_offset}&limit=#{limit}"
        else
          next_url = nil
        end

        render json: {
          battles: battles,
          next: next_url
        }, status: 200
      }

    end
  end

  def new
    @battle = Battle.new
  end

  def create
    battle = Battle.new(battle_params)
    respont_to do |format|
      format.html {
        if battle.save
          redirect_to battles_path
        else
          render action: 'new'
        end
      }
      format.json {
        if battle.save
          render json: @battle, status: 200
        else
          render json: @battle.errors, status: 422
        end
      }
    end
  end

  def show
    respond_to do |format|
      format.html

      format.json {
        render json: @battle, status: 200
      }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      format.html {
        if @battle.update(battle_params)
          redirect_to battles_path
        else
          render action: 'edit'
        end
      }

      format.json {
        if @battle.update(battle_params)
          render json: @battle, status: 200
        else
          render json: @battle.errors, status: 422
        end
      }
    end
  end

  def destroy
    respond_to do |format|
      format.html {
        @battle.destroy
        redirect_to battles_path
      }

      format.json {
        if @battle.destroy
          render json: {success: true}, status: 200
        else
          render json: @battle.errors, status: 422
        end
      }
    end
  end

  def stats
    battle_types = Battle.select("distinct(battle_type)").
      map(&:battle_type) - [nil]
    hash = {
      most_active: {
        attacker_king: Battle.highest_freq(:attacker_king),
        defender_king: Battle.highest_freq(:defender_king),
        region: Battle.highest_freq(:region),
        name: Battle.highest_freq(:name)
      },
      attacker_outcome: {
        win: Battle.where(attacker_outcome: 'win').count,
        loss: Battle.where(attacker_outcome: 'loss').count
      },
      battle_type: battle_types,
      defender_size: {
        average: Battle.average(:defender_size).to_i,
        min: Battle.maximum(:defender_size),
        max: Battle.minimum(:defender_size)
      }
    }
    render json: hash, status: 200
  end

  def list
    places = Battle.where.not(location: nil).distinct.pluck(:location)
    render json: {places: places}, status: 200
  end

  def count
    render json: { count: Battle.count }, status: 200
  end

  def search
    results = Battle.all
    searchable = [:name, :attacker_king, :defender_king, :location, :battle_type]
    searchable.each do |s|
      if params.has_key?(s)
        results = results.search(s, params[s])
      end
    end
    render json: {
      count: results.count,
      battles: results.order(:battle_number)
    }, status: 200
  end

  private

  def battle_params
    params.require(:battle).permit(:name, :year, :attacker_king, :defender_king,
      :attacker_1, :attacker_2, :attacker_3, :attacker_4, :defender_1,
      :defender_2, :defender_3, :defender_4, :attacker_outcome,
      :battle_type, :major_death, :major_capture, :attacker_size,
      :defender_size, :attacker_commander, :defender_commander,
      :summer, :location, :region, :note)
  end

  def load_battle
    @battle = Battle.find(params[:id])
  end

  def load_atrs
    @atrs = [:name, :attacker_king, :defender_king, :attacker_1,
      :attacker_2, :attacker_3, :attacker_4, :defender_1, :defender_2,
      :defender_3, :defender_4, :battle_type, :year, :major_death,
      :major_capture, :attacker_size, :defender_size,
      :attacker_commander, :defender_commander, :location, :region]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/battles/_form.html.erb
<%= form_for @battle do |form| %>
  <% @atrs.each do |atr| %>
    <%= "#{atr.to_s.capitalize}" %>
    <%= form.text_field atr %></br>
    <%= "#{atr.to_s.capitalize} #{@battle.errors[atr]}" unless @battle.errors[atr].empty? %></br>
  <% end %>
  <%= "Attacker Outcome" %>
  <%= form.radio_button(:attacker_outcome, :win) %> Win
  <%= form.radio_button(:attacker_outcome, :loss) %> Loss</br>
  <%= "Summer" %>
  <%= form.radio_button(:summer, :true) %> true
  <%= form.radio_button(:summer, :false) %> false</br>
  <%= "Note" %>
  <%= form.text_area :note %></br>
  <%= form.submit %>
<% end %>
<%= link_to 'Cancel', battles_path %>

app/views/battles/edit.html.erb
<%= render :partial => 'form' %>

app/views/battles/index.html.erb
<h1>List of Battles</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @battles.each do |battle| %>
    <tr>
      <td><%= link_to battle.name, battle %></td>
      <td>
        <%= link_to 'Edit', edit_battle_path(battle.battle_number) %>
        <%= link_to 'Delete', battle, :method => 'delete' %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Battle', new_battle_path %></p>

app/views/battles/new.html.erb
<%= render :partial => 'form' %>

app/views/battles/show.html.erb
<h1><%= @battle.name %></h1>

<table border='1'>
<% @battle.attributes.each do |key,val| %>
  <tr id=<%= key %>>
    <td><%= key.to_s.capitalize %></td>
    <td><%= val %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_battle_path %>
<%= link_to 'Back to home', battles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopprGotApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>